version: '3'
services:
  bookstore-mysql:
    image: mysql:latest
    container_name: bookstore_db_mysql
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack

  app:
    container_name: bookstore_app
    build: .
    ports:
      - "8081:8081"
    restart: always
    volumes:
      - api:/usr/src/app/
    depends_on:
      - bookstore-mysql
    networks:
      - fullstack

volumes:
  api:
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge