apiVersion: v1                           # API version
kind: Service                            # Type of kubernetes resource
metadata:
  name: bookstore-mysql                  # Name of the resource
  labels:                                # Labels that will be applied to the resource
    app: bookstore-mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:                              # Selects any Pod with labels `app=bookstore-mysql,tier=mysql`
    app: bookstore-mysql
